main.exe:main.o student.o teacher.o manager.o orderfile.o
	g++ main.o student.o teacher.o manager.o orderfile.o -o main.exe

main.o:main.cpp
	g++ -c main.cpp
student.o:student.cpp
	g++ -c student.cpp
teacher.o:teacher.cpp
	g++ -c teacher.cpp
manager.o:manager.cpp
	g++ -c manager.cpp
orderfile.o:orderfile.cpp
	g++ -c orderfile.cpp