main.exe:main.o workerManager.o person_type.o
	g++ main.o workerManager.o person_type.o -o main.exe

main.o:main.cpp
	g++ -c main.cpp
workerManager.o:workerManager.cpp
	g++ -c workerManager.cpp
person_type.o:person_type.cpp
	g++ -c person_type.cpp
